package com.notegym.back.model;
// Generated 7 abr 2026, 15:26:14 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name="group"
)
public class Group  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Timestamp creationdate;
     private Set<UserGroup> userGroups = new HashSet<>();

    public Group() {
    }

	
    public Group(String name, Timestamp creationdate) {
        this.name = name;
        this.creationdate = creationdate;
    }
    public Group(String name, String description, Timestamp creationdate, Set<UserGroup> userGroups) {
       this.name = name;
       this.description = description;
       this.creationdate = creationdate;
       this.userGroups = userGroups;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creationdate", nullable=false, length=19)
    public Timestamp getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Timestamp creationdate) {
        this.creationdate = creationdate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="group")
    public Set<UserGroup> getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(Set<UserGroup> userGroups) {
        this.userGroups = userGroups;
    }




}


