package com.notegym.back.model;
// Generated 7 abr 2026, 15:26:14 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name="log"
)
public class Log  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String description;
     private Timestamp timeOfLog;

    public Log() {
    }

    public Log(User user, String description, Timestamp timeOfLog) {
       this.user = user;
       this.description = description;
       this.timeOfLog = timeOfLog;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="description", nullable=false, length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_of_log", nullable=false, length=19)
    public Timestamp getTimeOfLog() {
        return this.timeOfLog;
    }
    
    public void setTimeOfLog(Timestamp timeOfLog) {
        this.timeOfLog = timeOfLog;
    }




}


