package com.notegym.back.model;
// Generated 23 mar 2026, 16:43:44 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
)
public class Message  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String content;
     private Timestamp sentAt;
     private int groupId;
     private Set userMessages = new HashSet(0);

    public Message() {
    }

	
    public Message(User user, String content, int groupId) {
        this.user = user;
        this.content = content;
        this.groupId = groupId;
    }
    public Message(User user, String content, Timestamp sentAt, int groupId, Set userMessages) {
       this.user = user;
       this.content = content;
       this.sentAt = sentAt;
       this.groupId = groupId;
       this.userMessages = userMessages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="content", nullable=false, length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sent_at", length=19)
    public Timestamp getSentAt() {
        return this.sentAt;
    }
    
    public void setSentAt(Timestamp sentAt) {
        this.sentAt = sentAt;
    }

    
    @Column(name="group_id", nullable=false)
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="message")
    public Set getUserMessages() {
        return this.userMessages;
    }
    
    public void setUserMessages(Set userMessages) {
        this.userMessages = userMessages;
    }




}


