package com.notegym.back.model;
// Generated 23 mar 2026, 16:43:44 by Hibernate Tools 6.4.8.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note")
public class Note implements java.io.Serializable {

    private int id;
    private User user;
    private Timestamp noteDate;
    private String text;
    private String name;

    public Note() {
    }

    public Note(int id, User user, Timestamp noteDate) {
        this.id = id;
        this.user = user;
        this.noteDate = noteDate;
    }

    public Note(int id, User user, Timestamp noteDate, String text, String name) {
        this.id = id;
        this.user = user;
        this.noteDate = noteDate;
        this.text = text;
        this.name = name;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "note_date", nullable = false, length = 19)
    public Timestamp getNoteDate() {
        return this.noteDate;
    }

    public void setNoteDate(Timestamp noteDate) {
        this.noteDate = noteDate;
    }

    @Column(name = "text", length = 150)
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
