package com.notegym.back.model;
// Generated 7 abr 2026, 15:26:14 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * UserGroup generated by hbm2java
 */
@Entity
@Table(name="user_group"
)
public class UserGroup  implements java.io.Serializable {


     private UserGroupId id;
     private Group group;
     private User user;
     private Timestamp registerDate;

    public UserGroup() {
    }

	
    public UserGroup(UserGroupId id, Group group, User user) {
        this.id = id;
        this.group = group;
        this.user = user;
    }
    public UserGroup(UserGroupId id, Group group, User user, Timestamp registerDate) {
       this.id = id;
       this.group = group;
       this.user = user;
       this.registerDate = registerDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="groupId", column=@Column(name="group_id", nullable=false) ), 
        @AttributeOverride(name="username", column=@Column(name="username", nullable=false, length=45) ) } )
    public UserGroupId getId() {
        return this.id;
    }
    
    public void setId(UserGroupId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id", nullable=false, insertable=false, updatable=false)
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="register_date", length=19)
    public Timestamp getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Timestamp registerDate) {
        this.registerDate = registerDate;
    }




}


