package com.notegym.back.model;
// Generated 7 abr 2026, 15:26:14 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * UserMessageId generated by hbm2java
 */
@Embeddable
public class UserMessageId  implements java.io.Serializable {


     private int messageId;
     private String userId;

    public UserMessageId() {
    }

    public UserMessageId(int messageId, String userId) {
       this.messageId = messageId;
       this.userId = userId;
    }
   


    @Column(name="message_id", nullable=false)
    public int getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(int messageId) {
        this.messageId = messageId;
    }


    @Column(name="user_id", nullable=false, length=45)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserMessageId) ) return false;
		 UserMessageId castOther = ( UserMessageId ) other; 
         
		 return (this.getMessageId()==castOther.getMessageId())
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getMessageId();
        result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         return result;
   }   


}


