package com.notegym.back.model;
// Generated 23 mar 2026, 16:43:44 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    , uniqueConstraints = {@UniqueConstraint(columnNames="mail"), @UniqueConstraint(columnNames="user_token")} 
)
public class User  implements java.io.Serializable {


     private String username;
     private String name;
     private String mail;
     private String sex;
     private String role;
     private Timestamp registdate;
     private String userToken;
     private String password;
     private Integer triesLogIn;
     private Boolean blocked;
     private Set workouts = new HashSet(0);
     private Set userMessages = new HashSet(0);
     private Set logs = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set userGroups = new HashSet(0);
     private Set notes = new HashSet(0);
     private Set exercises = new HashSet(0);
     private Set exercises_1 = new HashSet(0);
     private Set workouts_1 = new HashSet(0);
     private Set warnings = new HashSet(0);

    public User() {
    }

	
    public User(String username, String mail, String role, String password) {
        this.username = username;
        this.mail = mail;
        this.role = role;
        this.password = password;
    }
    public User(String username, String name, String mail, String sex, String role, Timestamp registdate, String userToken, String password, Integer triesLogIn, Boolean blocked, Set workouts, Set userMessages, Set logs, Set messages, Set userGroups, Set notes, Set exercises, Set exercises_1, Set workouts_1, Set warnings) {
       this.username = username;
       this.name = name;
       this.mail = mail;
       this.sex = sex;
       this.role = role;
       this.registdate = registdate;
       this.userToken = userToken;
       this.password = password;
       this.triesLogIn = triesLogIn;
       this.blocked = blocked;
       this.workouts = workouts;
       this.userMessages = userMessages;
       this.logs = logs;
       this.messages = messages;
       this.userGroups = userGroups;
       this.notes = notes;
       this.exercises = exercises;
       this.exercises_1 = exercises_1;
       this.workouts_1 = workouts_1;
       this.warnings = warnings;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="mail", unique=true, nullable=false, length=55)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="sex", length=45)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    
    @Column(name="role", nullable=false, length=45)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registdate", length=19)
    public Timestamp getRegistdate() {
        return this.registdate;
    }
    
    public void setRegistdate(Timestamp registdate) {
        this.registdate = registdate;
    }

    
    @Column(name="user_token", unique=true, length=150)
    public String getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }

    
    @Column(name="password", nullable=false, length=150)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="triesLogIn")
    public Integer getTriesLogIn() {
        return this.triesLogIn;
    }
    
    public void setTriesLogIn(Integer triesLogIn) {
        this.triesLogIn = triesLogIn;
    }

    
    @Column(name="blocked")
    public Boolean getBlocked() {
        return this.blocked;
    }
    
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_workout", catalog="notegym", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="workout_id", nullable=false, updatable=false) })
    public Set getWorkouts() {
        return this.workouts;
    }
    
    public void setWorkouts(Set workouts) {
        this.workouts = workouts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getUserMessages() {
        return this.userMessages;
    }
    
    public void setUserMessages(Set userMessages) {
        this.userMessages = userMessages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(Set userGroups) {
        this.userGroups = userGroups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set notes) {
        this.notes = notes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getExercises() {
        return this.exercises;
    }
    
    public void setExercises(Set exercises) {
        this.exercises = exercises;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_exercise", catalog="notegym", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="exercise_id", nullable=false, updatable=false) })
    public Set getExercises_1() {
        return this.exercises_1;
    }
    
    public void setExercises_1(Set exercises_1) {
        this.exercises_1 = exercises_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getWorkouts_1() {
        return this.workouts_1;
    }
    
    public void setWorkouts_1(Set workouts_1) {
        this.workouts_1 = workouts_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set getWarnings() {
        return this.warnings;
    }
    
    public void setWarnings(Set warnings) {
        this.warnings = warnings;
    }




}










