package com.notegym.back.model;
// Generated 23 mar 2026, 16:43:44 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * UserMessage generated by hbm2java
 */
@Entity
@Table(name="user_message"
)
public class UserMessage  implements java.io.Serializable {


     private UserMessageId id;
     private User user;
     private Message message;
     private Timestamp sendDate;

    public UserMessage() {
    }

    public UserMessage(UserMessageId id, User user, Message message, Timestamp sendDate) {
       this.id = id;
       this.user = user;
       this.message = message;
       this.sendDate = sendDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="messageId", column=@Column(name="message_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false, length=45) ) } )
    public UserMessageId getId() {
        return this.id;
    }
    
    public void setId(UserMessageId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="message_id", nullable=false, insertable=false, updatable=false)
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="send_date", nullable=false, length=19)
    public Timestamp getSendDate() {
        return this.sendDate;
    }
    
    public void setSendDate(Timestamp sendDate) {
        this.sendDate = sendDate;
    }




}


