package com.notegym.back.model;
// Generated 7 abr 2026, 15:26:14 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;


/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    , uniqueConstraints = {@UniqueConstraint(columnNames="mail"), @UniqueConstraint(columnNames="user_token")} 
)
public class User  implements java.io.Serializable {


     private String username;
     private String name;
     private String mail;
     private String sex;
     private String role;
     private Timestamp registdate;
     private String userToken;
     private String password;
     private Integer triesLogIn;
     private Boolean blocked;
     private Set<Workout> workouts = new HashSet<>();
     private Set<UserMessage> userMessages = new HashSet<>();
     private Set<Log> logs = new HashSet<>();
     private Set<Message> messages = new HashSet<>();
     private Set<UserGroup> userGroups = new HashSet<>();
     private Set<Note> notes = new HashSet<>();
     private Set<Exercise> exercises = new HashSet<>();
     private Set<Exercise> exercises_1 = new HashSet<>();
     private Set<Workout> workouts_1 = new HashSet<>();
     private Set<Warning> warnings = new HashSet<>();

    public User() {
    }

	
    public User(String username, String mail, String role, String password) {
        this.username = username;
        this.mail = mail;
        this.role = role;
        this.password = password;
    }
    public User(String username, String name, String mail, String sex, String role, Timestamp registdate, String userToken, String password, Integer triesLogIn, Boolean blocked, Set<Workout> workouts, Set<UserMessage> userMessages, Set<Log> logs, Set<Message> messages, Set<UserGroup> userGroups, Set<Note> notes, Set<Exercise> exercises, Set<Exercise> exercises_1, Set<Workout> workouts_1, Set<Warning> warnings) {
       this.username = username;
       this.name = name;
       this.mail = mail;
       this.sex = sex;
       this.role = role;
       this.registdate = registdate;
       this.userToken = userToken;
       this.password = password;
       this.triesLogIn = triesLogIn;
       this.blocked = blocked;
       this.workouts = workouts;
       this.userMessages = userMessages;
       this.logs = logs;
       this.messages = messages;
       this.userGroups = userGroups;
       this.notes = notes;
       this.exercises = exercises;
       this.exercises_1 = exercises_1;
       this.workouts_1 = workouts_1;
       this.warnings = warnings;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="mail", unique=true, nullable=false, length=55)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="sex", length=45)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    
    @Column(name="role", nullable=false, length=45)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registdate", length=19)
    public Timestamp getRegistdate() {
        return this.registdate;
    }
    
    public void setRegistdate(Timestamp registdate) {
        this.registdate = registdate;
    }

    
    @Column(name="user_token", unique=true, length=150)
    public String getUserToken() {
        return this.userToken;
    }
    
    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }

    
    @Column(name="password", nullable=false, length=150)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="triesLogIn")
    public Integer getTriesLogIn() {
        return this.triesLogIn;
    }
    
    public void setTriesLogIn(Integer triesLogIn) {
        this.triesLogIn = triesLogIn;
    }

    
    @Column(name="blocked")
    public Boolean getBlocked() {
        return this.blocked;
    }
    
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_workout", catalog="notegym", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="workout_id", nullable=false) })
    public Set<Workout> getWorkouts() {
        return this.workouts;
    }
    
    public void setWorkouts(Set<Workout> workouts) {
        this.workouts = workouts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserMessage> getUserMessages() {
        return this.userMessages;
    }
    
    public void setUserMessages(Set<UserMessage> userMessages) {
        this.userMessages = userMessages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Log> getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set<Log> logs) {
        this.logs = logs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserGroup> getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(Set<UserGroup> userGroups) {
        this.userGroups = userGroups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Exercise> getExercises() {
        return this.exercises;
    }
    
    public void setExercises(Set<Exercise> exercises) {
        this.exercises = exercises;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_exercise", catalog="notegym", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="exercise_id", nullable=false) })
    public Set<Exercise> getExercises_1() {
        return this.exercises_1;
    }
    
    public void setExercises_1(Set<Exercise> exercises_1) {
        this.exercises_1 = exercises_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Workout> getWorkouts_1() {
        return this.workouts_1;
    }
    
    public void setWorkouts_1(Set<Workout> workouts_1) {
        this.workouts_1 = workouts_1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Warning> getWarnings() {
        return this.warnings;
    }
    
    public void setWarnings(Set<Warning> warnings) {
        this.warnings = warnings;
    }




}


