package com.notegym.back.model;
// Generated 23 mar 2026, 16:43:44 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * UserGroupId generated by hbm2java
 */
@Embeddable
public class UserGroupId  implements java.io.Serializable {


     private int groupId;
     private String username;

    public UserGroupId() {
    }

    public UserGroupId(int groupId, String username) {
       this.groupId = groupId;
       this.username = username;
    }
   


    @Column(name="group_id", nullable=false)
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }


    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserGroupId) ) return false;
		 UserGroupId castOther = ( UserGroupId ) other; 
         
		 return (this.getGroupId()==castOther.getGroupId())
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getGroupId();
        result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         return result;
   }   


}


