package com.notegym.back.model;
// Generated 7 abr 2026, 15:26:14 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Warning generated by hbm2java
 */
@Entity
@Table(name="warning"
)
public class Warning  implements java.io.Serializable {


     private int id;
     private User user;
     private String reason;
     private Long timeout;
     private Timestamp date;

    public Warning() {
    }

	
    public Warning(int id, User user, String reason, Timestamp date) {
        this.id = id;
        this.user = user;
        this.reason = reason;
        this.date = date;
    }
    public Warning(int id, User user, String reason, Long timeout, Timestamp date) {
       this.id = id;
       this.user = user;
       this.reason = reason;
       this.timeout = timeout;
       this.date = date;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="reason", nullable=false, length=150)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="timeout")
    public Long getTimeout() {
        return this.timeout;
    }
    
    public void setTimeout(Long timeout) {
        this.timeout = timeout;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Timestamp getDate() {
        return this.date;
    }
    
    public void setDate(Timestamp date) {
        this.date = date;
    }




}


