package com.notegym.back.model;
// Generated 7 abr 2026, 15:26:14 by Hibernate Tools 6.4.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Workout generated by hbm2java
 */
@Entity
@Table(name="workout"
)
public class Workout  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String description;
     private String name;
     private Set<User> users = new HashSet<>();
     private Set<Exercise> exercises = new HashSet<>();

    public Workout() {
    }

	
    public Workout(User user, String name) {
        this.user = user;
        this.name = name;
    }
    public Workout(User user, String description, String name, Set<User> users, Set<Exercise> exercises) {
       this.user = user;
       this.description = description;
       this.name = name;
       this.users = users;
       this.exercises = exercises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@JsonIgnore
@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_workout", catalog="notegym", joinColumns = { 
        @JoinColumn(name="workout_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_id", nullable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="workout_exercise", catalog="notegym", joinColumns = { 
        @JoinColumn(name="workout_id", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="exersice_id", nullable=false) })
    public Set<Exercise> getExercises() {
        return this.exercises;
    }
    
    public void setExercises(Set<Exercise> exercises) {
        this.exercises = exercises;
    }




}


