spring.application.name=back

spring.datasource.url=jdbc:mariadb://bbddnotegym.cbkqaouukgbq.eu-west-3.rds.amazonaws.com:3306/notegym
spring.datasource.username=admin
spring.datasource.password=Asdqwe123_?#


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.file.name=logs/notegym.log
logging.level.root = INFO

application.security.jwt.secret-key=BFyC7nYjZJY82F4j6lPTiKWukg0fajB54PXFXe7bzwx
application.security.jwt.expiration=86400000
application.security.jwt.refreshtoken=604800000 