
hibernate.connection.driver_class=org.mariadb.jdbc.Driver

hibernate.connection.url=jdbc:mariadb://bbddnotegym.cbkqaouukgbq.eu-west-3.rds.amazonaws.com:3306/notegym
hibernate.connection.username=admin
hibernate.connection.password="Asdqwe123_?#"


hibernate.dialect=org.hibernate.dialect.MariaDBDialect